# Generated by Django 3.2.16 on 2023-01-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeforpost',
            name='timestamp',
        ),
    ]
