# Generated by Django 3.2.16 on 2022-11-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_remove_uploadimage_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='image_id',
            field=models.IntegerField(default=0),
        ),
    ]
