# Generated by Django 3.2.16 on 2023-01-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_remove_likeforpost_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='image_id',
        ),
    ]
