# Generated by Django 3.2.16 on 2023-01-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_remove_uploadimage_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimage',
            old_name='temprature',
            new_name='temperature',
        ),
    ]
