# Generated by Django 3.2.16 on 2023-01-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_rename_temprature_uploadimage_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='sum_like',
            field=models.IntegerField(default=0),
        ),
    ]
